cmake_minimum_required(VERSION 3.14)
project(pressure_core_tests LANGUAGES CXX)
add_executable(core_test core_test.cpp)
target_compile_features(core_test PRIVATE cxx_std_17)
if(MSVC)
  target_compile_options(core_test PRIVATE /W4 /WX /UNDEBUG)
else()
  target_compile_options(core_test PRIVATE -Wall -Wextra -Werror -UNDEBUG)
endif()
